### ISSUE TITLE
Random test failures

### ISSUE THREAD

**Issue by eserte** [skington/data-tersify#4]
t/tersify.t fails sometimes like this:
http://www.cpantesters.org/cpan/report/02a23f70-66f9-11ea-9066-e374b0ba08e8

At the time of writing, the fail:pass ratio on CPAN Testers is 29:298. See http://matrix.cpantesters.org/?dist=Data-Tersify+1.000

**Comment by skington** [comment]
Yeah, I've been looking at that, and I can't spot a pattern yet.

**Comment by eserte** [comment]
There is no pattern regarding perl configuration or OS version --- if running t/tersify.t in a loop, then it usually fails after less than 200 iterations.

**Comment by skington** [comment]
Ahah! Found it. Thank you very much!

**Comment by skington** [comment]
I believe this is now [fixed](https://github.com/skington/data-tersify/commit/ad6b1f1f9b4dbd3aebb1664c7f6991ac0e4a95a6), so I'm going to close this issue. Feel free to re-open it (or open a new one) if you find the same problem. Again, thank you!
